---
title: "PEGASUS Global Metabolomics Primary Analyses"
subtitle: "All three platforms"
author: "MHuang"
date: "12/22/2020"
output: 
  html_document: 
    toc: yes
    toc_float: 
      collapsed: false
      smooth_scroll: false
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include = F}

## Packages

pkg <- c("tidyverse", "data.table", "here", "survival", "gtools", "DT", "table1")
for (p in pkg) {
        if (require(p, character.only = T)) {
                print(paste0(p, " loaded successfully"))
        } else {
                install.packages(p)
                require(p, character.only = T)
                print(paste0(p, " downloaded and loaded successfully"))
        }
}


## Paths

dat_dir <- "C:/Users/MHuang/Dropbox (Partners HealthCare)/PEGASUS/global_metabolomics_082020/pegasus_global_data_qc/post_qc_data/"
pheno_dir <- "C:/Users/MHuang/Dropbox (Partners HealthCare)/PEGASUS/rpdr_data/rpdr_data_wrangling_analyses/data/"
fig_dir <- "figures/"
res_dir <- "results/"


## Filenames

all_subj_fname <- str_c(pheno_dir, "all_subj_enc_bmi.csv")
med_cs_fname <- str_c(pheno_dir, "med_corticosteroids_summary.csv")
wbc_fname <- str_c(pheno_dir, "wbc_count_closest_to_serum_collection.csv")
exac_fname <- str_c(pheno_dir, "asthma_exacerbation_summary.csv")
comorb_fname <- str_c(pheno_dir, "comorbidities_of_interest.csv")

hilic_pos_fname <- str_c(dat_dir, "hilic_pos/outlier_checked/processed_hilic_pos_halfmin.RData")
lipid_pos_fname <- str_c(dat_dir, "lipid_pos/processed_lipid_pos_halfmin.RData")
lipid_neg_fname <- str_c(dat_dir, "lipid_neg/processed_lipid_neg_halfmin.RData")


## Hard-coded numbers

missing_thld <- 0.30
sig_digits <- 3
alpha_thld <- 0.05
z_95 <- qnorm(p = 0.975)
mrg_by_cols <- c("sampleID_biobank", "SampleGroup", "Match_ID", "Asthma_Status", 
                 "Age", "Gender", "Race", "BMI", "Nonsmoker")
num_cols <- c("beta", "pval", "fdr_bh", "or", "lower95", "upper95", "pct_na_met", "cv")

```

# 1. Data assembly
## 1.1. Phenotype/EMR data

```{r}

all_subj <- fread(all_subj_fname)
all_subj[, Collect_Date := as.Date(Collect_Date, format = "%Y-%m-%d")]
all_subj[, .N, .(is.na(EMPI), is.na(Collect_Date))][order(is.na, is.na.1)] %>% 
        setnames(., c("missing_EMPI", "missing_Collect_Date", "N")) %>% print()
all_subj[, asthma_num := case_when(Asthma_Status == TRUE ~ 1, 
                                   Asthma_Status == FALSE ~ 0)]

med_cs <- fread(med_cs_fname)
pheno <- merge(all_subj[!is.na(EMPI), ], med_cs, by = c("EMPI", "SampleGroup"), all.x = T)

comorb <- fread(comorb_fname)
pheno <- merge(pheno, comorb[!is.na(EMPI), ], by = c("EMPI"), all.x = T)

wbc <- fread(wbc_fname)
pheno <- merge(pheno, wbc, by = c("EMPI"), all.x = T)

exac <- fread(exac_fname)
pheno <- merge(pheno, exac, by = c("EMPI", "SampleGroup"), all.x = T)

```

## 1.2. Global metabolomics data
### 1.2.1. HILIC-positive halfmin imputed data (outlier checked)

```{r}

load(hilic_pos_fname, verbose = T)
hilic_pos_mets_info <- copy(mets_info)


## Merge with pheno data

hilic_pos_dat <- merge(pheno, samp_dat_final, by = mrg_by_cols)


## Add indicators for platform, medication & without MS2

hilic_pos_mets_info[, platform := "HILIC-pos"]

meds_string <- str_c("Flutrimazole|Bezafibrate|Esomeprazole|Levocetirizine|Paracetamol|Irbesartan|",
                     "Gabapentin|Fexofenadine|Isosorbide|Lisofylline|Venlafaxine|Nortriptyline|Metformin|", 
                     "Escitalopram|Methocarbamol|Dantrolene|Trimethoprim|Sulfamethoxazole|Thioguanine|", 
                     "Thalidomide|Diazepam|Trazodone|Levetiracetam|Diltiazem|Fenoterol|Eflornithine|", 
                     "Carbetapentane|Fluoxetine|Fluconazole|Metronidazole")

hilic_pos_mets_info[tentative_annotation != "Unknown", 
                    ':='(wo_ms2 = case_when(grepl("(?i)w/o ms2", tentative_annotation) ~ 1, 
                                            TRUE ~ 0), 
                         med_feat = case_when(grepl(meds_string, tentative_annotation, ignore.case = T) ~ 1, 
                                              TRUE ~ 0))]


## Manually annotate cortisol (F1381, confirmed with standard by Pei)

hilic_pos_mets_info[feature == "F1381", tentative_annotation := "Cortisol"]


## Remove original metabolomic data files with non-specific names

rm(mets_info, samp_dat_final, samp_dat_origscale, samp_na, samp_mets_cols)

```

### 1.2.2. Lipidomics-positive halfmin imputed data

```{r}

load(lipid_pos_fname, verbose = T)
lipid_pos_mets_info <- copy(mets_info)


## Check if feature IDs overlap

lipid_pos_mets_info[, .N, feature %in% hilic_pos_mets_info[, feature]]
# Lots of features with same feature ID, cannot simply combine data


## Merge with pheno data

setnames(samp_dat_final, "Group", "SampleGroup")
lipid_pos_dat <- merge(pheno, samp_dat_final, by = mrg_by_cols)


## Add indicators for platform & without MS2

lipid_pos_mets_info[, platform := "Lipid-pos"]
lipid_pos_mets_info[tentative_annotation != "Unknown", 
                    ':='(wo_ms2 = case_when(grepl("(?i)w/o ms2", tentative_annotation) ~ 1, 
                                            TRUE ~ 0), 
                         med_feat = 0)] 


## Change feature annotated to mouse/cell metabolites to unknown

lipid_pos_mets_info[grepl("(?i)mouse|cell", tentative_annotation), tentative_annotation := "Unknown"]


## Remove original metabolomic data files with non-specific names

rm(mets_info, samp_dat_final, samp_dat_origscale, samp_na, samp_mets_cols)

```

### 1.2.3. Lipidomics-negative halfmin imputed data

```{r}

load(lipid_neg_fname, verbose = T)
lipid_neg_mets_info <- copy(mets_info)


## Check if feature IDs overlap

lipid_neg_mets_info[, .N, feature %in% hilic_pos_mets_info[, feature]]
# Lots of features with same feature ID, cannot simply combine data


## Merge with pheno data

setnames(samp_dat_final, "Group", "SampleGroup")
lipid_neg_dat <- merge(pheno, samp_dat_final, by = mrg_by_cols)


## Add indicators for platform & without MS2

lipid_neg_mets_info[, platform := "Lipid-pos"]
lipid_neg_mets_info[tentative_annotation != "Unknown", 
                    ':='(wo_ms2 = case_when(grepl("(?i)w/o ms2", tentative_annotation) ~ 1, 
                                            TRUE ~ 0), 
                         med_feat = 0)] 


## Change feature annotated to mouse/cell metabolites to unknown

lipid_neg_mets_info[grepl("(?i)mouse|cell", tentative_annotation), tentative_annotation := "Unknown"]


## Remove original metabolomic data files with non-specific names

rm(mets_info, samp_dat_final, samp_dat_origscale, samp_na, samp_mets_cols)

```

# Session info

```{r}

sessionInfo()

```
